# Generated by Django 5.1.5 on 2025-02-18 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coupon",
            options={"verbose_name": "Купон", "verbose_name_plural": "Купоны"},
        ),
    ]
