# Generated by Django 5.1.5 on 2025-02-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_adress_order_address_rename_emal_order_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stripe_id",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=False, verbose_name="Статус оплаты"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="count",
            field=models.PositiveIntegerField(default=1, verbose_name="Количество"),
        ),
    ]
