# Generated by Django 5.1.5 on 2025-02-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_stripe_id_alter_order_paid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="E-mail"),
        ),
    ]
